server:
  port: 9999

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/steveaurel/config
          default-label: master
          clone-on-start: true
          skip-ssl-validation: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
